### ISSUE TITLE
一个题外话

### ISSUE THREAD

**Issue by kuazhangxiaoai** [hukaixuan19970627/YOLOv5_DOTA_OBB#125]
## Additional context
大神，您在DOTAv1.5上试过YOLOX吗？感觉baseline就不好，才60左右，您能有什么建议吗？

**Comment by hukaixuan19970627** [comment]
yolox的exp文件截个图看看？
确定是按照dota的benchmark参数测出来的baseline吗

**Comment by kuazhangxiaoai** [comment]
exp文件等一下，您说的dota的benchmark是指的什么？
overlap=200+img-size=1024*1024+single-scale。

**Comment by hukaixuan19970627** [comment]
> exp文件等一下，您说的dota的benchmark是指的什么？ overlap=200，img-size=1024*1024，single-scale。

如果为60的话，确实偏低，也就比retinanet-obb高了一点点，应该是改建过程中出了啥问题。
![image](https://user-images.githubusercontent.com/72599120/146512606-36344cbc-1e5f-416f-9eac-b87575a9c9b9.png)
你用的YOLOX-OBB是自己改的吗，还是哪个开源项目的？我自己这几天改建了一个，还没跑完呢，2张2080ti跑dotav1.5 150epoch需要3天，目前跑到50个epoch了，从可视化的感觉上来看效果似乎要比yolov5的差。

而且yolox的坑不少，要改的地方还挺多的，simOTA那里，我把样本的角度评估也加了进去，结果运行的时候一直出“OOM RuntimeError is raised due to the huge memory cost during label assignment”提示，一直自动用cpu运行，为了训练速度，所以simOTA那儿我就没改，准备之后做对比实验看看没加角度评估的simOTA对旋转检测的精度影响有多大。

还有一个地方是yolox的数据增强函数一次iter中调用的次数比较多，每个数据增强函数为了防止label超出图像范围都会np.clip一下，这个步骤对检测poly的检测器没啥影响，但是对检测rotated rectangle的检测器影响就比较大了，训练前poly会转成rotated rectangle，这个时候边缘处的物体求出来的矩形角度就是错误的。为了防止这一点，我是注释掉np.clip，用检测poly中心点是否在图像范围内以此来滤除gt的，这样可以一定程度上确保检测器能够通过物体的部分区域来判断完整物体的真实大小和角度，不过也存在问题，像下图中，部分飞机因为中心点刚好超出原始图像外，就直接被滤除掉了，感觉对最终精度稍微会有点影响。如果确定要用yolox来做旋转检测的话，这部分数据增强最好还是重写一下，用yolov5的mixup、mosaic处理逻辑会比较好。
![image](https://user-images.githubusercontent.com/72599120/146515378-52d66fc3-d93a-4a78-9bef-2605fe524f87.png)

我对目前正在跑的yolox的期待值是yolox-m 在 dotav1.5上的单尺度测试mAP >= 69，不比yolov5高的话就没必要用了，毕竟yolox的训练速度和参数量是都要比yolov5高不少的

**Comment by hukaixuan19970627** [comment]
> exp文件等一下，您说的dota的benchmark是指的什么？ overlap=200，img-size=1024*1024，single-scale。 数据处理过程和您的YOLOv5差不多。 代码地址：https://github.com/kuazhangxiaoai/yolox-pytorch 数据处理代码地址：https://github.com/kuazhangxiaoai/DOTA_devkit_YOLO

这是HBB的吧

**Comment by kuazhangxiaoai** [comment]
> > exp文件等一下，您说的dota的benchmark是指的什么？ overlap=200，img-size=1024*1024，single-scale。 数据处理过程和您的YOLOv5差不多。 代码地址：https://github.com/kuazhangxiaoai/yolox-pytorch 数据处理代码地址：https://github.com/kuazhangxiaoai/DOTA_devkit_YOLO
> 
> 这是HBB的吧
这是OBB的YOLOX，用的开源项目是https://github.com/bubbliiiing/yolox-pytorch

**Comment by kuazhangxiaoai** [comment]
> > exp文件等一下，您说的dota的benchmark是指的什么？ overlap=200，img-size=1024*1024，single-scale。 数据处理过程和您的YOLOv5差不多。 代码地址：https://github.com/kuazhangxiaoai/yolox-pytorch 数据处理代码地址：https://github.com/kuazhangxiaoai/DOTA_devkit_YOLO
> 
> 这是HBB的吧

是的，我也用的是不加angle的simOTA，我还使用了原版OTA，原版OTA比simOTA能提高2个点。但是原版OTA比较慢，所以需要前80%用simOTA，后20%用原版OTA。

**Comment by hukaixuan19970627** [comment]
我这边跑的dotav1.5的baseline mAP为65左右，只能说跟yolov5差不多，一般般。而且关闭mosaic后验证集的mAP会一直掉，和别的检测器上的结果不一致

**Comment by kuazhangxiaoai** [comment]
大神，我的YOLOX 怎么差了这么多? 您用的是官方版本的YOLOX吗？

**Comment by hukaixuan19970627** [comment]
> 大神，我的YOLOX 怎么差了这么多? 您用的是官方版本的YOLOX吗？

嗯，有官方的肯定用官方的撒。yolox-m ，用了coco上的预训练模型，你是train from scratch 吗

**Comment by kuazhangxiaoai** [comment]
> > 大神，我的YOLOX 怎么差了这么多? 您用的是官方版本的YOLOX吗？
> 
> 嗯，有官方的肯定用官方的撒。yolox-m ，用了coco上的预训练模型，你是train from scratch 吗

不是，我也用了预训练模型，跑了80左右的epoach，但也不能差这么多吧，我也用的是yoloxm

**Comment by hukaixuan19970627** [comment]
> > > 大神，我的YOLOX 怎么差了这么多? 您用的是官方版本的YOLOX吗？
> > 
> > 
> > 嗯，有官方的肯定用官方的撒。yolox-m ，用了coco上的预训练模型，你是train from scratch 吗
> 
> 不是，我也用了预训练模型，跑了80左右的epoach，但也不能差这么多吧，我也用的是yoloxm ![image](https://user-images.githubusercontent.com/54108453/146885323-985b1517-848d-401a-b283-186fd4e7ee2c.png)
> 
> 对了，您用swin-transformer的预训练模型的话，在哪下载呢？1024乘1024的swin-transformer的模型结构能加载上640乘640的预训练模型参数吗？

swin-transformer在使用上和普通的backbone没有区别，参数量是固定的，跟输入图像的分辨率没关系

**Comment by hukaixuan19970627** [comment]
https://github.com/hukaixuan19970627/OrientedRepPoints_DOTA
swin的官方预训练模型的下载链接我copy到readme里了

**Comment by hukaixuan19970627** [comment]
> > > 大神，我的YOLOX 怎么差了这么多? 您用的是官方版本的YOLOX吗？
> > 
> > 
> > 嗯，有官方的肯定用官方的撒。yolox-m ，用了coco上的预训练模型，你是train from scratch 吗
> 
> 不是，我也用了预训练模型，跑了80左右的epoach，但也不能差这么多吧，我也用的是yoloxm ![image](https://user-images.githubusercontent.com/54108453/146885323-985b1517-848d-401a-b283-186fd4e7ee2c.png)
> 
> 对了，您用swin-transformer的预训练模型的话，在哪下载呢？1024乘1024的swin-transformer的模型结构能加载上640乘640的预训练模型参数吗？

我训了150epoch，不过性能最好的是last mosaic epoch ckpt

**Comment by hukaixuan19970627** [comment]
刚更新了一版yolov5-obb， yolov5m直接训可以做到单尺度测试 DOTAv1.5 mAP上73，很强。直接比我老版本的最佳精度还高了5个点

**Comment by kuazhangxiaoai** [comment]
真是太强了
